dssat_read_summary_out <- function(x){
  readr::read_table(file = x,
                    skip = 3,
                    col_types = readr::cols(
                      .default = readr::col_integer(),
                      `@` = readr::col_character(),
                      CR = readr::col_character(),
                      MODEL... = readr::col_character(),
                      TNAM..................... = readr::col_character(),
                      FNAM.... = readr::col_character(),
                      WSTA.... = readr::col_character(),
                      SOIL_ID... = readr::col_character(),
                      SDAT = readr::col_character(),
                      PDAT = readr::col_character(),
                      EDAT = readr::col_character(),
                      ADAT = readr::col_character(),
                      MDAT = readr::col_character(),
                      HDAT = readr::col_character(),
                      HWUM = readr::col_double(),
                      `H#UM` = readr::col_double(),
                      HIAM = readr::col_double(),
                      LAIX = readr::col_double(),
                      DMPPM = readr::col_double(),
                      DMPEM = readr::col_double(),
                      DMPTM = readr::col_double(),
                      YPPM = readr::col_double(),
                      YPEM = readr::col_double(),
                      YPTM = readr::col_double(),
                      TMAXA = readr::col_double(),
                      TMINA = readr::col_double(),
                      SRADA = readr::col_double(),
                      DAYLA = readr::col_double())) %>%
    dplyr::mutate(SDAT = as.Date(SDAT, format = "%Y%j"),
                  PDAT = as.Date(PDAT, format = "%Y%j"),
                  EDAT = as.Date(EDAT, format = "%Y%j"),
                  ADAT = as.Date(ADAT, format = "%Y%j"),
                  MDAT = as.Date(MDAT, format = "%Y%j"),
                  HDAT = as.Date(HDAT, format = "%Y%j"))
}
